# Generated by Django 3.1.3 on 2020-11-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defence', '0003_post_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('company_email', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='default.jpg', upload_to='company')),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('details', models.TextField()),
                ('created', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
